server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

spring:
  application:
    name: project-assistant
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/projectdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  web:
    resources:
      static-locations: classpath:/static/,file:./service_data/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.timelordtty.projectassistant.entity
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    root: info
    com.timelordtty.projectassistant: debug
  file:
    path: ./service_data/logs
    org.springframework.web: info
    org.mybatis: info 