-- 项目表
CREATE TABLE IF NOT EXISTS project (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '项目名称',
    description VARCHAR(500) COMMENT '项目描述',
    start_date DATE COMMENT '开始日期',
    end_date DATE COMMENT '结束日期',
    manager VARCHAR(50) COMMENT '项目经理',
    status VARCHAR(20) DEFAULT 'PLANNING' COMMENT '项目状态：PLANNING, IN_PROGRESS, COMPLETED, CANCELLED',
    budget DECIMAL(15, 2) COMMENT '项目预算',
    priority INT DEFAULT 1 COMMENT '优先级：1(低)~5(高)',
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
); 