server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: project-assistant-service
  datasource:
    url: jdbc:h2:file:./data/projectdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.timelordtty.projectcalendar.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 日志配置
logging:
  level:
    root: INFO
    com.timelordtty: DEBUG
    org.mybatis: INFO

# 百度API配置
baidu:
  text-correction:
    api-key: your_api_key_here
    secret-key: your_secret_key_here
    url: https://aip.baidubce.com/rpc/2.0/nlp/v1/ecnet 